### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'outputGephi'

### ISSUE THREAD

**Issue by polom** [Gjacquenot/gedcomTools#1]
Bonjour,

Je ne suis pas super expérimenté en Python. J'ai réussi à installer les modules requis mais lorsque je lance le script avec mes deux arguments (gedcom en entrée et gefx à créer en sortie) j'ai le message d'erreur suivant : 

`Traceback (most recent call last):
  File "gedcom2gexf.py", line 37, in <module>
    gedcom2gephi(gedcomFilename = args.gedcom, gephiFilename = args.outputGephi)
AttributeError: 'Namespace' object has no attribute 'outputGephi'`

Je ne sais pas bien quoi faire :(

**Comment by Gjacquenot** [comment]
Il y a effectivement un problème au niveau du parser: une erreur de copier-coller. Pouvez-vous récupérer la nouvelle version et tester à nouveau?

**Comment by polom** [comment]
On progresse :)
Mais j'ai maintenant ceci : 
`Traceback (most recent call last):
  File "gedcom2gexf.py", line 38, in <module>
    gedcom2gephi(gedcomFilename=args.gedcom, gephiFilename=args.outputGexf)
  File "gedcom2gexf.py", line 18, in gedcom2gephi
    dg.add_node(getId(p), {'label':getName(p), 'name':getName(p), 'familyName':getFamilyName(p)})
TypeError: add_node() takes 2 positional arguments but 3 were given`

**Comment by Gjacquenot** [comment]
J'ai corrigé encore une erreur de keyword argument.  Pouvez-vous récupérer la nouvelle version et tester à nouveau?

**Comment by polom** [comment]
On progresse, mais il en reste :
`Traceback (most recent call last):
  File "gedcom2gexf.py", line 38, in <module>
    gedcom2gephi(gedcomFilename=args.gedcom, gephiFilename=args.outputGexf)
  File "gedcom2gexf.py", line 20, in gedcom2gephi
    if p.father:
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/gedcom/__init__.py", line 498, in father
    male_parents = [p for p in self.parents if p.is_male]
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/gedcom/__init__.py", line 371, in parents
    family_as_child_id = self['FAMC'].value
AttributeError: 'list' object has no attribute 'value'`

**Comment by Gjacquenot** [comment]
Le message d'erreur montre que le problème ne vient peut-être pas du code , mais soit du fichier d'entrées soit de la bibliothèque `gedcompy`.

J'ai refait un test chez moi avec un fichier `.ged` généré avec `Gramps` et je n'ai pas eu d'erreur.
Par ailleurs, j'ai été imprécis sur les dépendances: le fichier requirements.txt était erroné: pouvez-vous vérifier que vous avez la même version que moi en exécutant cette commande dans votre terminal?

    $ python -c 'import gedcom; print(gedcom.__version__)'
    0.2.9

J'utilise la version 0.2.9 de `gedcompy`, que j'ai installé avec la commande:

    $ python -m pip install gedcompy

Si par hasard, je vous ai fait installer la mauvaise bibliothèque,  vous pouvez la désinstaller avec

    $ python -m pip uninstall python-gedcom

`sudo` peut être nécessaire pour installer/désinstaller des paquets python.

Si le problème vient du code, il faut débugger.
Pour débugger, avec les bonnes bibliothèques:

- soit vous m'envoyez votre fichier `.ged` que je regarde (pas top pour votre confidentialité)
- soit vous essayez de trouver l'origine du bug en insérant les lignes `print(p); print(type(p)); print(p.father);` avant `if p.father`

Je pense que c'est un problème avec la dépendance python

**Comment by polom** [comment]
J'ai bien la bonne version de gedcompy, installée à coups de sudo. Et mon fichier vient de Gramps (mais repris via Webtrees). Je viens de re-tester avec une autre version (un backup généré par Gramps). 
J'ai ajouté du debug et le problème se trouve sur un individu précis (mon I16023). Je vais explorer. 
J'ai lancé une vérification / réparation de la BDD dans Gramps, ça n'a rien signalé de particulier en dehors de fichiers médias disparus. J'ai ré-exporté mon fichier GEDCOM, retesté, et ça plante au même endroit. Dans Gramps je ne vois rien de notable pour la personne concernée ou son père.
J'ai testé avec :
- un export sans les vivants, limité aux ascendants de la personne : OK
- un export sans les vivants, limité aux descendants de la personne : OK
- un export sans les vivants, limité aux familles descendantes de la personne : OK
- un export sans les vivants, avec tous les individus : KO

Le message d'erreur final étant `    family_as_child_id = self['FAMC'].value
AttributeError: 'list' object has no attribute 'value'` je comprends que le père concerné (celui de mon individu I16023) n'aurait pas l'attribut FAMC ?
Ce qui m'intrigue c'est que je n'aie pas ce soucis quand je prends les ascendants ou les descendants de I16023.

**Comment by polom** [comment]
Précision complémentaire au sujet du père (I0357), j'ai une note dans sa fiche qui indique :

> Enregistrements non-importés dans INDI (individu) Gramps ID I0357:
> 
> Reconnu mais non-supporté (TAG)                                     Line  3789: 2 ASSO @I900@
> Ligne suivante ignorée                                              Line  3790: 3 TYPE INDI
> Ligne suivante ignorée                                              Line  3791: 3 RELA Attending
> Ligne suivante ignorée                                              Line  3792: 3 NOTE sage femme
> Reconnu mais non-supporté (TAG)                                     Line  3793: 2 ASSO @I899@
> Ligne suivante ignorée                                              Line  3794: 3 TYPE INDI
> Ligne suivante ignorée                                              Line  3795: 3 RELA Attending
> Ligne suivante ignorée                                              Line  3796: 3 NOTE oncle ?
> Reconnu mais non-supporté (TAG)                                     Line  3797: 2 ASSO @I270@
> Ligne suivante ignorée                                              Line  3798: 3 TYPE INDI
> Ligne suivante ignorée                                              Line  3799: 3 RELA Attending
> Reconnu mais non-supporté (TAG)                                     Line  3805: 2 ASSO @I6296@
> Ligne suivante ignorée                                              Line  3806: 3 TYPE INDI
> Ligne suivante ignorée                                              Line  3807: 3 RELA Registry officer
> Reconnu mais non-supporté (TAG)                                     Line  3808: 2 ASSO @I6295@
> Ligne suivante ignorée                                              Line  3809: 3 TYPE INDI
> Ligne suivante ignorée                                              Line  3810: 3 RELA Attending
> Reconnu mais non-supporté (TAG)                                     Line  3812: 2 ASSO @I273@
> Ligne suivante ignorée                                              Line  3813: 3 TYPE INDI
> Ligne suivante ignorée                                              Line  3814: 3 RELA Informant

**Comment by polom** [comment]
Et j'ai finalement mis le doigt sur le souci : l'individu i16083 avait deux familles, celle avec ses deux parents et une avec son père uniquement. J'ai supprimé cette dernière et tout fonctionne.
