### ISSUE TITLE
cannot find a module gedcom

### ISSUE THREAD

**Issue by qgenesist** [Gjacquenot/gedcomTools#2]
i can find python-gedcom is that the import I should use?

**Comment by Gjacquenot** [comment]
Code is not well documented on dependency. gedcom parser is provided by package gedcompy.

The following command will install this dependency

    python -m pip install gedcompy

This package may collide with python-gedcom. So uninstall first python-gedcom before installing gedcompy. `python -m pip uninstall python-gedcom`

**Comment by qgenesist** [comment]
thank you ever so much for the reply.  should my import be:
import gedcom
or
import gedcompy

(I am an absolute beginner in Python.  And github.


________________________________

**Comment by Gjacquenot** [comment]
Well, it should be `import gedcom`.

You can have a look at documentation [here](https://gedcompy.readthedocs.io/en/latest/)

Here is an example of how you can use it

    import gedcom
    gedcomfile = gedcom.parse("myfamilytree.ged")
    for person in gedcomfile.individuals:
        firstname, lastname = person.name
        print("{0} {1} is in the file".format(firstname, lastname))

If it answers your question, you can close the issue.
